//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> "#"
 * f1 -> "include"
 * f2 -> ( <STRING_LITERAL> | Include() )
 */
public class IncludeStatement implements Node {
   public NodeToken f0;
   public NodeToken f1;
   public NodeChoice f2;

   public IncludeStatement(NodeToken n0, NodeToken n1, NodeChoice n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
   }

   public IncludeStatement(NodeChoice n0) {
      f0 = new NodeToken("#");
      f1 = new NodeToken("include");
      f2 = n0;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

